library(shiny)

source(file.path("R", "effect_distribution.R"), local = TRUE)
effects <- readRDS(file.path("data", "effects.rds"))
app_directory <- normalizePath(getwd(), mustWork = TRUE)

field_labels <- c(
  SP = "Social psychology",
  IDP = "Individual differences",
  CP = "Cognitive psychology"
)
conversion_labels <- c(
  anova_f_df1 = "ANOVA F (df1 = 1)",
  pearson_r = "Pearson r",
  t_paired_or_one_sample = "Paired / one-sample t",
  student_t_independent = "Independent-samples t",
  ols_coefficient_t = "OLS coefficient t",
  chi_square_df1 = "Chi-square (df = 1)",
  logistic_coefficient_z = "Logistic coefficient z",
  cohen_d_independent = "Independent-groups Cohen's d"
)
between_metric_choices <- c(
  "r" = "r",
  "d" = "d",
  "r² / partial η²" = "r_squared",
  "f" = "f",
  "Odds ratio" = "odds_ratio"
)

available_fields <- names(field_labels)[names(field_labels) %in% unique(effects$field)]
available_bases <- names(conversion_labels)[
  names(conversion_labels) %in% unique(effects$r_conversion_basis)
]
available_journals <- sort(unique(effects$journal))
year_limits <- range(effects$year, na.rm = TRUE)

filter_group <- function(title, content) {
  tags$details(
    class = "filter-group",
    tags$summary(title),
    tags$div(class = "filter-group-content", content)
  )
}

shinylive_download_button <- function(...) {
  button <- shiny::downloadButton(...)
  # Chromium blocks service-worker-backed Shinylive downloads when the anchor
  # has a download attribute (Chromium issue 468227).
  button$attribs$download <- NULL
  button
}

quartile_summary <- function(distribution) {
  if (is.null(distribution) || !isTRUE(distribution$ready)) {
    return(NULL)
  }

  labels <- c(
    "25th percentile (small)",
    "50th percentile (medium)",
    "75th percentile (large)"
  )
  tags$div(
    class = "quartile-summary",
    Map(function(label, value) {
      tags$div(
        class = "quartile-stat",
        tags$span(class = "quartile-label", label),
        tags$strong(class = "quartile-value", sprintf("%.2f", value))
      )
    }, labels, distribution$quartiles)
  )
}

r_assignment <- function(name, value) {
  value_text <- capture.output(dput(value))
  value_text[1] <- paste0(name, " <- ", value_text[1])
  value_text
}

build_reproduction_script <- function(filters, between_metric = "r") {
  configuration <- c(
    r_assignment("search_terms", filters$keyword),
    r_assignment("selected_fields", filters$fields),
    r_assignment("selected_conversion_bases", filters$conversion_bases),
    r_assignment("selected_preregistration", filters$preregistration),
    r_assignment("selected_year_range", filters$year_range),
    r_assignment("selected_journals", filters$journals),
    r_assignment("selected_between_metric", between_metric)
  )
  calculation_code <- readLines(
    file.path(app_directory, "R", "effect_distribution.R"),
    warn = FALSE
  )

  c(
    "# Reproduce an Empirical effect size distibution explorer result",
    "# Generated by the Shiny app. Requires base R only.",
    "",
    configuration,
    "",
    calculation_code,
    "",
    "effects <- read.csv(",
    "  \"effects.csv\",",
    "  stringsAsFactors = FALSE,",
    "  check.names = FALSE,",
    "  na.strings = c(\"\", \"NA\")",
    ")",
    "",
    "filtered_effects <- filter_effects(",
    "  effects,",
    "  keyword = search_terms,",
    "  fields = selected_fields,",
    "  conversion_bases = selected_conversion_bases,",
    "  preregistration = selected_preregistration,",
    "  year_range = selected_year_range,",
    "  journals = selected_journals",
    ")",
    "",
    "between_specification <- between_metric_spec(selected_between_metric)",
    "between <- transform_between_distribution(",
    "  prepare_effect_distribution(filtered_effects, \"between\"),",
    "  selected_between_metric",
    ")",
    "within <- prepare_effect_distribution(filtered_effects, \"within\")",
    "",
    "estimate_rows <- function(distribution, design, metric) {",
    "  estimates <- if (isTRUE(distribution$ready)) distribution$quartiles else rep(NA_real_, 3)",
    "  data.frame(",
    "    design = design,",
    "    metric = metric,",
    "    percentile = c(25, 50, 75),",
    "    magnitude = c(\"small\", \"medium\", \"large\"),",
    "    estimate = estimates,",
    "    n_articles = if (isTRUE(distribution$ready)) distribution$studies else NA_integer_,",
    "    k_effects = distribution$usable_effects",
    "  )",
    "}",
    "",
    "quartile_estimates <- rbind(",
    "  estimate_rows(between, \"Between-subjects\", between_specification$label),",
    "  estimate_rows(within, \"Within-subjects\", \"bias-corrected dz\")",
    ")",
    "write.csv(quartile_estimates, \"quartile_estimates.csv\", row.names = FALSE)",
    "print(quartile_estimates)",
    "",
    "grDevices::pdf(\"weighted_histograms.pdf\", width = 11, height = 5.5)",
    "old_par <- graphics::par(mfrow = c(1, 2))",
    "draw_effect_histogram(between, \"#2f6fa6\", between_specification$x_label)",
    "draw_effect_histogram(within, \"#6a93b8\", \"Effect size (bias-corrected dz)\")",
    "graphics::par(old_par)",
    "grDevices::dev.off()",
    "",
    "cat(\"\\nMatching effects:\", nrow(filtered_effects), \"\\n\")",
    "cat(\"Created quartile_estimates.csv and weighted_histograms.pdf\\n\")"
  )
}

write_reproduction_package <- function(result, file) {
  package_directory <- tempfile("effect-reproduction-")
  dir.create(package_directory)
  on.exit(unlink(package_directory, recursive = TRUE, force = TRUE), add = TRUE)

  write.csv(
    effects,
    file.path(package_directory, "effects.csv"),
    row.names = FALSE,
    na = ""
  )
  writeLines(
    build_reproduction_script(
      result$filters,
      if (is.null(result$between_metric)) "r" else result$between_metric
    ),
    file.path(package_directory, "reproduce.R"),
    useBytes = TRUE
  )
  writeLines(
    c(
      "Empirical effect size distibution explorer reproduction package",
      "",
      "Contents:",
      "- effects.csv: complete application dataset",
      "- reproduce.R: active filters and all code needed to reproduce the result",
      "",
      "Place both files in the same directory, open R there, and run:",
      "  source(\"reproduce.R\")",
      "",
      "The script writes quartile_estimates.csv and weighted_histograms.pdf.",
      "It uses base R only and does not calculate confidence intervals."
    ),
    file.path(package_directory, "README.txt")
  )

  archive_file <- file.path(
    normalizePath(dirname(file), mustWork = TRUE),
    basename(file)
  )
  old_directory <- setwd(package_directory)
  on.exit(setwd(old_directory), add = TRUE)
  utils::tar(
    tarfile = archive_file,
    files = c("effects.csv", "reproduce.R", "README.txt"),
    compression = "gzip",
    tar = "internal"
  )
  invisible(archive_file)
}

ui <- fluidPage(
  tags$head(
    tags$title("Empirical effect size distibution explorer"),
    tags$meta(name = "viewport", content = "width=device-width, initial-scale=1"),
    tags$link(rel = "stylesheet", type = "text/css", href = "styles.css")
  ),
  tags$header(
    class = "app-header",
    tags$div(
      class = "header-inner",
      tags$h1("Empirical effect size distibution explorer")
    )
  ),
  tags$aside(
    class = "study-info",
    tags$p(
      "These effects were extracted as part of Azaad (2026). ",
      tags$em(
        "Empirically derived effect size guidelines for social, individual ",
        "differences, and cognitive psychology."
      ),
      " ",
      tags$a(
        href = "https://osf.io/preprints/psyarxiv/r4xwb_v1",
        target = "_blank",
        rel = "noopener noreferrer",
        "https://osf.io/preprints/psyarxiv/r4xwb_v1"
      ),
      ". Method and validation information can be found in the preprint."
    )
  ),
  tags$main(
    class = "app-shell",
    tags$aside(
      class = "filter-panel",
      tags$div(
        class = "filter-heading",
        tags$h2("Search dataset")
      ),
      textInput(
        "keyword",
        "Keywords or phrases",
        placeholder = "e.g. memory, attention"
      ),
      tags$p(
        class = "input-help",
        "Comma-separated terms match any term across keywords, claim, title, and description."
      ),
      actionButton(
        "calculate",
        "Calculate distributions",
        class = "calculate-button"
      ),
      tags$p(
        class = "calculate-note",
        "Changes are applied only when you click calculate."
      ),
      tags$div(class = "divider"),
      tags$h3(class = "filters-title", "Filters"),
      filter_group(
        "Field",
        checkboxGroupInput(
          "field",
          NULL,
          choices = stats::setNames(available_fields, field_labels[available_fields]),
          selected = available_fields
        )
      ),
      filter_group(
        "Test type",
        tags$div(
          class = "scroll-checklist",
          checkboxGroupInput(
            "conversion_basis",
            NULL,
            choices = stats::setNames(available_bases, conversion_labels[available_bases]),
            selected = available_bases
          )
        )
      ),
      filter_group(
        "Preregistration",
        radioButtons(
          "preregistration",
          NULL,
          choices = c(
            "All" = "all",
            "Preregistered" = "preregistered",
            "Not preregistered" = "not_preregistered"
          ),
          selected = "all"
        )
      ),
      filter_group(
        "Publication year",
        sliderInput(
          "year_range",
          NULL,
          min = year_limits[1],
          max = year_limits[2],
          value = year_limits,
          step = 1,
          sep = ""
        )
      ),
      filter_group(
        "Journal",
        tags$div(
          class = "scroll-checklist journal-checklist",
          checkboxGroupInput(
            "journal",
            NULL,
            choices = available_journals,
            selected = available_journals
          )
        )
      )
    ),
    tags$section(
      class = "results-panel",
      uiOutput("result_header"),
      tags$div(
        class = "chart-grid",
        tags$article(
          class = "chart-card",
          tags$div(
            class = "chart-title-row",
            tags$div(class = "design-marker marker-between"),
            tags$div(
              tags$h3("Between-subjects designs"),
              uiOutput("between_metric_description")
            )
          ),
          plotOutput("between_plot", height = "365px"),
          uiOutput("between_quartiles"),
          tags$div(
            class = "metric-control",
            tags$span(class = "metric-control-label", "Display as"),
            radioButtons(
              "between_metric",
              NULL,
              choices = between_metric_choices,
              selected = "r",
              inline = TRUE
            )
          )
        ),
        tags$article(
          class = "chart-card",
          tags$div(
            class = "chart-title-row",
            tags$div(class = "design-marker marker-within"),
            tags$div(
              tags$h3("Within-subjects designs"),
              tags$p("Bias-corrected effect size measured as dz")
            )
          ),
          plotOutput("within_plot", height = "365px"),
          uiOutput("within_quartiles")
        )
      ),
      tags$div(
        class = "method-note",
        tags$strong("How weighting works"),
        tags$p(
          "Bars use inverse-variance random-effects weights. Each article's ",
          "contribution is divided across its effects before bin proportions are ",
          "calculated. Dashed lines show the mean weighted quartiles from 5,000 ",
          "article-cluster bootstrap samples, with one effect sampled per ",
          "article/study. Confidence intervals are not included."
        ),
        tags$p(
          "Between-subjects conversions transform the calculated r values and ",
          "quartile thresholds while retaining the r-scale weights. The odds-ratio ",
          "histogram uses a logarithmic x-axis; on converted scales, the rightmost ",
          "bin includes values at or above its labelled boundary. The d conversion ",
          "assumes equal group sizes, r² corresponds to partial η² for one-degree-",
          "of-freedom effects, and odds ratios use the logistic approximation."
        )
      ),
      uiOutput("reproduction_download_ui")
    )
  )
)

server <- function(input, output, session) {
  calculation <- reactiveVal(NULL)

  between_display <- reactive({
    result <- calculation()
    if (is.null(result)) {
      return(NULL)
    }
    transform_between_distribution(result$between, input$between_metric)
  })

  observeEvent(input$calculate, {
    selected <- filter_effects(
      effects,
      keyword = input$keyword,
      fields = input$field,
      conversion_bases = input$conversion_basis,
      preregistration = input$preregistration,
      year_range = input$year_range,
      journals = input$journal
    )

    withProgress(message = "Calculating weighted distributions", value = 0, {
      incProgress(0.1, detail = "Filtering effects")
      between <- prepare_effect_distribution(selected, "between")
      incProgress(0.45, detail = "Between-subjects distribution")
      within <- prepare_effect_distribution(selected, "within")
      incProgress(0.45, detail = "Within-subjects distribution")

      calculation(list(
        keyword = trimws(input$keyword),
        filters = list(
          keyword = trimws(input$keyword),
          fields = input$field,
          conversion_bases = input$conversion_basis,
          preregistration = input$preregistration,
          year_range = input$year_range,
          journals = input$journal
        ),
        filtered = selected,
        between = between,
        within = within
      ))
    })
  }, ignoreInit = TRUE)

  output$result_header <- renderUI({
    result <- calculation()
    if (is.null(result)) {
      return(tags$div(
        class = "results-intro",
        tags$div(
          tags$h2("No results calculated"),
          tags$p("Enter search terms or adjust filters, then click Calculate distributions.")
        )
      ))
    }

    search_label <- if (nzchar(result$keyword)) {
      paste0(" for “", result$keyword, "”")
    } else {
      ""
    }
    tags$div(
      class = "results-heading",
      tags$div(
        tags$p(class = "results-kicker", "RESULTS"),
        tags$h2(paste0(format(nrow(result$filtered), big.mark = ","),
          " matching effects", search_label))
      ),
      tags$div(
        class = "result-counts",
        tags$span(
          class = "count-chip chip-between",
          paste(format(result$between$usable_effects, big.mark = ","), "between")
        ),
        tags$span(
          class = "count-chip chip-within",
          paste(format(result$within$usable_effects, big.mark = ","), "within")
        )
      )
    )
  })

  output$between_plot <- renderPlot({
    specification <- between_metric_spec(input$between_metric)
    draw_effect_histogram(between_display(), "#2f6fa6", specification$x_label)
  }, res = 110)

  output$between_metric_description <- renderUI({
    tags$p(between_metric_spec(input$between_metric)$subtitle)
  })

  output$within_plot <- renderPlot({
    result <- calculation()
    distribution <- if (is.null(result)) NULL else result$within
    draw_effect_histogram(distribution, "#6a93b8", "Effect size (bias-corrected dz)")
  }, res = 110)

  output$between_quartiles <- renderUI({
    quartile_summary(between_display())
  })

  output$within_quartiles <- renderUI({
    result <- calculation()
    quartile_summary(if (is.null(result)) NULL else result$within)
  })

  output$reproduction_download_ui <- renderUI({
    if (is.null(calculation())) {
      return(NULL)
    }
    tags$div(
      class = "download-panel",
      tags$div(
        tags$strong("Reproduce this result"),
        tags$p(
          "Download the complete data and one standalone base-R script containing ",
          "the active search, filters, calculations, and plotting code."
        )
      ),
      shinylive_download_button(
        "download_reproduction",
        "Download reproduction package",
        class = "reproduction-button"
      )
    )
  })

  output$download_reproduction <- downloadHandler(
    filename = function() {
      paste0("effect-distribution-reproduction-", Sys.Date(), ".tar.gz")
    },
    contentType = "application/gzip",
    content = function(file) {
      result <- calculation()
      req(result)
      result$between_metric <- input$between_metric
      write_reproduction_package(result, file)
    }
  )
}

shinyApp(ui, server)
