project_libraries <- file.path(c(getwd(), dirname(getwd())), ".local-r-library")
for (project_library in project_libraries) {
  if (file.exists(file.path(project_library, "zcurve", "DESCRIPTION")) &&
      as.character(utils::packageVersion("zcurve", lib.loc = project_library)) == "2.4.2") {
    .libPaths(c(project_library, .libPaths()))
    break
  }
}

library(shiny)

source(file.path("R", "effect_distribution.R"), local = TRUE)
source(file.path("R", "zcurve.R"), local = TRUE)
effects <- readRDS(file.path("data", "effects.rds"))
app_directory <- normalizePath(getwd(), mustWork = TRUE)

field_labels <- c(
  SP = "Social psychology",
  IDP = "Individual differences",
  CP = "Cognitive psychology"
)
conversion_labels <- c(
  anova_f_df1 = "ANOVA F (df1 = 1)",
  pearson_r = "Pearson r",
  t_paired_or_one_sample = "Paired / one-sample t",
  student_t_independent = "Independent-samples t",
  ols_coefficient_t = "OLS coefficient t",
  chi_square_df1 = "Chi-square (df = 1)",
  logistic_coefficient_z = "Logistic coefficient z",
  cohen_d_independent = "Independent-groups Cohen's d"
)
between_metric_choices <- c(
  "r" = "r",
  "d" = "d",
  "r² / partial η²" = "r_squared",
  "f" = "f",
  "Odds ratio" = "odds_ratio"
)

available_fields <- names(field_labels)[names(field_labels) %in% unique(effects$field)]
available_bases <- names(conversion_labels)[
  names(conversion_labels) %in% unique(effects$r_conversion_basis)
]
available_journals <- sort(unique(effects$journal))
year_limits <- range(effects$year, na.rm = TRUE)

filter_group <- function(title, content) {
  tags$details(
    class = "filter-group",
    tags$summary(title),
    tags$div(class = "filter-group-content", content)
  )
}

shinylive_download_button <- function(...) {
  button <- shiny::downloadButton(...)
  # Chromium blocks service-worker-backed Shinylive downloads when the anchor
  # has a download attribute (Chromium issue 468227).
  button$attribs$download <- NULL
  button
}

quartile_summary <- function(distribution) {
  if (is.null(distribution) || !isTRUE(distribution$ready)) {
    return(NULL)
  }

  labels <- c(
    "25th percentile (small)",
    "50th percentile (medium)",
    "75th percentile (large)"
  )
  tags$div(
    class = "quartile-summary",
    Map(function(label, value) {
      tags$div(
        class = "quartile-stat",
        tags$span(class = "quartile-label", label),
        tags$strong(class = "quartile-value", sprintf("%.2f", value))
      )
    }, labels, distribution$quartiles)
  )
}

r_assignment <- function(name, value) {
  value_text <- capture.output(dput(value))
  value_text[1] <- paste0(name, " <- ", value_text[1])
  value_text
}

build_reproduction_script <- function(filters, between_metric = "r") {
  configuration <- c(
    r_assignment("search_terms", filters$keyword),
    r_assignment("selected_fields", filters$fields),
    r_assignment("selected_conversion_bases", filters$conversion_bases),
    r_assignment("selected_preregistration", filters$preregistration),
    r_assignment("selected_year_range", filters$year_range),
    r_assignment("selected_journals", filters$journals),
    r_assignment("selected_between_metric", between_metric)
  )
  calculation_code <- readLines(
    file.path(app_directory, "R", "effect_distribution.R"),
    warn = FALSE
  )

  c(
    "# Reproduce an Empirical effect size distibution explorer result",
    "# Generated by the Shiny app. Requires base R only.",
    "",
    configuration,
    "",
    calculation_code,
    "",
    "effects <- read.csv(",
    "  \"effects.csv\",",
    "  stringsAsFactors = FALSE,",
    "  check.names = FALSE,",
    "  na.strings = c(\"\", \"NA\")",
    ")",
    "",
    "filtered_effects <- filter_effects(",
    "  effects,",
    "  keyword = search_terms,",
    "  fields = selected_fields,",
    "  conversion_bases = selected_conversion_bases,",
    "  preregistration = selected_preregistration,",
    "  year_range = selected_year_range,",
    "  journals = selected_journals",
    ")",
    "",
    "between_specification <- between_metric_spec(selected_between_metric)",
    "between <- transform_between_distribution(",
    "  prepare_effect_distribution(filtered_effects, \"between\"),",
    "  selected_between_metric",
    ")",
    "within <- prepare_effect_distribution(filtered_effects, \"within\")",
    "",
    "estimate_rows <- function(distribution, design, metric) {",
    "  estimates <- if (isTRUE(distribution$ready)) distribution$quartiles else rep(NA_real_, 3)",
    "  data.frame(",
    "    design = design,",
    "    metric = metric,",
    "    percentile = c(25, 50, 75),",
    "    magnitude = c(\"small\", \"medium\", \"large\"),",
    "    estimate = estimates,",
    "    n_articles = if (isTRUE(distribution$ready)) distribution$studies else NA_integer_,",
    "    k_effects = distribution$usable_effects",
    "  )",
    "}",
    "",
    "quartile_estimates <- rbind(",
    "  estimate_rows(between, \"Between-subjects\", between_specification$label),",
    "  estimate_rows(within, \"Within-subjects\", \"bias-corrected dz\")",
    ")",
    "write.csv(quartile_estimates, \"quartile_estimates.csv\", row.names = FALSE)",
    "print(quartile_estimates)",
    "",
    "grDevices::pdf(\"weighted_histograms.pdf\", width = 11, height = 5.5)",
    "old_par <- graphics::par(mfrow = c(1, 2))",
    "draw_effect_histogram(between, \"#2f6fa6\", between_specification$x_label)",
    "draw_effect_histogram(within, \"#6a93b8\", \"Effect size (bias-corrected dz)\")",
    "graphics::par(old_par)",
    "grDevices::dev.off()",
    "",
    "cat(\"\\nMatching effects:\", nrow(filtered_effects), \"\\n\")",
    "cat(\"Created quartile_estimates.csv and weighted_histograms.pdf\\n\")"
  )
}

build_zcurve_refit_script <- function(filters, cluster_by, bootstraps) {
  c(
    "# Refit the analysis with zcurve 2.4.2 using the saved search and filters.",
    'if (!requireNamespace("zcurve", quietly = TRUE)) stop("Install the zcurve package first.")',
    'if (as.character(utils::packageVersion("zcurve")) != "2.4.2") stop("Install zcurve 2.4.2 for this refit.")',
    r_assignment("search_terms", filters$keyword),
    r_assignment("selected_fields", filters$fields),
    r_assignment("selected_conversion_bases", filters$conversion_bases),
    r_assignment("selected_preregistration", filters$preregistration),
    r_assignment("selected_year_range", filters$year_range),
    r_assignment("selected_journals", filters$journals),
    r_assignment("cluster_by", cluster_by),
    r_assignment("bootstraps", bootstraps),
    "",
    readLines(file.path(app_directory, "R", "effect_distribution.R"), warn = FALSE),
    "",
    readLines(file.path(app_directory, "R", "zcurve.R"), warn = FALSE),
    "",
    'effects <- read.csv("effects.csv", stringsAsFactors = FALSE, na.strings = c("", "NA"))',
    "filtered <- filter_effects(effects, search_terms, selected_fields,",
    "  selected_conversion_bases, selected_preregistration, selected_year_range,",
    "  selected_journals)",
    "prepared <- prepare_zcurve_effects(filtered)",
    "result <- fit_clustered_zcurve(prepared, cluster_by, bootstraps)",
    'if (!result$ready) stop(result$reason)',
    "estimates <- data.frame(metric = rownames(result$estimates),",
    "  result$estimates, row.names = NULL, check.names = FALSE)",
    'write.csv(estimates, "refit_estimates.csv", row.names = FALSE)',
    'grDevices::pdf("refit_zcurve.pdf", width = 9, height = 6)',
    "draw_zcurve(result)",
    "grDevices::dev.off()",
    "print(estimates)"
  )
}

build_zcurve_reproduction_script <- function() {
  c(
    "# Display the exact fitted object downloaded from the Shinylive session.",
    'if (!requireNamespace("zcurve", quietly = TRUE)) stop("Install zcurve 2.4.2 first.")',
    'if (as.character(utils::packageVersion("zcurve")) != "2.4.2") stop("Install zcurve 2.4.2 first.")',
    'model <- readRDS("zcurve_fit.rds")',
    'estimates <- read.csv("zcurve_estimates.csv", check.names = FALSE)',
    "print(estimates)",
    'grDevices::pdf("reproduced_zcurve.pdf", width = 9, height = 6)',
    'graphics::plot(model, CI = TRUE, annotation = TRUE, plot_type = "base", cex.anno = 0.75)',
    "grDevices::dev.off()",
    'cat("Run source(\\"refit.R\\") for a fresh fit from the data.\\n")'
  )
}

write_zcurve_reproduction_package <- function(result, file) {
  stopifnot(isTRUE(result$ready), !is.null(result$model), !is.null(result$prepared))
  directory <- tempfile("zcurve-reproduction-")
  dir.create(directory)
  on.exit(unlink(directory, recursive = TRUE, force = TRUE), add = TRUE)
  write.csv(effects, file.path(directory, "effects.csv"), row.names = FALSE, na = "")
  saveRDS(result$model, file.path(directory, "zcurve_fit.rds"), version = 2)
  write.csv(data.frame(metric = rownames(result$estimates), result$estimates,
    row.names = NULL, check.names = FALSE),
    file.path(directory, "zcurve_estimates.csv"), row.names = FALSE)
  write.csv(result$prepared, file.path(directory, "zcurve_effects.csv"),
    row.names = FALSE, na = "")
  grDevices::pdf(file.path(directory, "zcurve.pdf"), width = 9, height = 6)
  tryCatch(draw_zcurve(result), finally = grDevices::dev.off())
  writeLines(build_zcurve_reproduction_script(),
    file.path(directory, "reproduce.R"), useBytes = TRUE)
  writeLines(build_zcurve_refit_script(result$filters, result$cluster_by,
    result$bootstraps), file.path(directory, "refit.R"), useBytes = TRUE)
  writeLines(c("Clustered z-curve reproduction package", "",
    "The session's exact fitted object, estimates, calculated p-values, and",
    "package plot are saved as zcurve_fit.rds, zcurve_estimates.csv,",
    "zcurve_effects.csv, and zcurve.pdf.",
    "Requires zcurve 2.4.2 for an exact match to the Shinylive build.",
    "Run source(\"reproduce.R\") to read the saved fit and draw the package plot.",
    "Run source(\"refit.R\") to fit again from effects.csv with the saved filters",
    "and seed. A fresh fit may differ in its last floating-point digit across",
    "native R and webR."),
    file.path(directory, "README.txt"))
  archive <- file.path(normalizePath(dirname(file), mustWork = TRUE), basename(file))
  old_directory <- setwd(directory)
  on.exit(setwd(old_directory), add = TRUE)
  utils::tar(archive, c("effects.csv", "zcurve_fit.rds", "zcurve_estimates.csv",
    "zcurve_effects.csv", "zcurve.pdf", "reproduce.R", "refit.R", "README.txt"),
    compression = "gzip", tar = "internal")
}

write_reproduction_package <- function(result, file) {
  package_directory <- tempfile("effect-reproduction-")
  dir.create(package_directory)
  on.exit(unlink(package_directory, recursive = TRUE, force = TRUE), add = TRUE)

  write.csv(
    effects,
    file.path(package_directory, "effects.csv"),
    row.names = FALSE,
    na = ""
  )
  writeLines(
    build_reproduction_script(
      result$filters,
      if (is.null(result$between_metric)) "r" else result$between_metric
    ),
    file.path(package_directory, "reproduce.R"),
    useBytes = TRUE
  )
  writeLines(
    c(
      "Empirical effect size distibution explorer reproduction package",
      "",
      "Contents:",
      "- effects.csv: complete application dataset",
      "- reproduce.R: active filters and all code needed to reproduce the result",
      "",
      "Place both files in the same directory, open R there, and run:",
      "  source(\"reproduce.R\")",
      "",
      "The script writes quartile_estimates.csv and weighted_histograms.pdf.",
      "It uses base R only and does not calculate confidence intervals."
    ),
    file.path(package_directory, "README.txt")
  )

  archive_file <- file.path(
    normalizePath(dirname(file), mustWork = TRUE),
    basename(file)
  )
  old_directory <- setwd(package_directory)
  on.exit(setwd(old_directory), add = TRUE)
  utils::tar(
    tarfile = archive_file,
    files = c("effects.csv", "reproduce.R", "README.txt"),
    compression = "gzip",
    tar = "internal"
  )
  invisible(archive_file)
}

ui <- fluidPage(
  tags$head(
    tags$title("Empirical effect size distibution explorer"),
    tags$meta(name = "viewport", content = "width=device-width, initial-scale=1"),
    tags$link(rel = "stylesheet", type = "text/css", href = "styles.css")
  ),
  tags$header(
    class = "app-header",
    tags$div(
      class = "header-inner",
      tags$h1("Empirical effect size distibution explorer")
    )
  ),
  tags$aside(
    class = "study-info",
    tags$p(
      "These effects were extracted as part of Azaad (2026). ",
      tags$em(
        "Empirically derived effect size guidelines for social, individual ",
        "differences, and cognitive psychology."
      ),
      " ",
      tags$a(
        href = "https://osf.io/preprints/psyarxiv/r4xwb_v1",
        target = "_blank",
        rel = "noopener noreferrer",
        "https://osf.io/preprints/psyarxiv/r4xwb_v1"
      ),
      ". Method and validation information can be found in the preprint."
    )
  ),
  tags$main(
    class = "app-shell",
    tags$aside(
      class = "filter-panel",
      tags$div(
        class = "filter-heading",
        tags$h2("Search dataset")
      ),
      textInput(
        "keyword",
        "Keywords or phrases",
        placeholder = "e.g. memory, attention"
      ),
      tags$p(
        class = "input-help",
        "Comma-separated terms match any term across keywords, title, and description."
      ),
      actionButton(
        "calculate",
        "Calculate distributions",
        class = "calculate-button"
      ),
      tags$p(
        class = "calculate-note",
        "Changes are applied only when you click calculate."
      ),
      tags$div(class = "divider"),
      tags$h3(class = "filters-title", "Filters"),
      filter_group(
        "Field",
        checkboxGroupInput(
          "field",
          NULL,
          choices = stats::setNames(available_fields, field_labels[available_fields]),
          selected = available_fields
        )
      ),
      filter_group(
        "Test type",
        tags$div(
          class = "scroll-checklist",
          checkboxGroupInput(
            "conversion_basis",
            NULL,
            choices = stats::setNames(available_bases, conversion_labels[available_bases]),
            selected = available_bases
          )
        )
      ),
      filter_group(
        "Preregistration",
        radioButtons(
          "preregistration",
          NULL,
          choices = c(
            "All" = "all",
            "Preregistered" = "preregistered",
            "Not preregistered" = "not_preregistered"
          ),
          selected = "all"
        )
      ),
      filter_group(
        "Publication year",
        sliderInput(
          "year_range",
          NULL,
          min = year_limits[1],
          max = year_limits[2],
          value = year_limits,
          step = 1,
          sep = ""
        )
      ),
      filter_group(
        "Journal",
        tags$div(
          class = "scroll-checklist journal-checklist",
          checkboxGroupInput(
            "journal",
            NULL,
            choices = available_journals,
            selected = available_journals
          )
        )
      )
    ),
    tags$section(
      class = "results-panel",
      tabsetPanel(id = "view", type = "tabs",
        tabPanel("ES distributions", value = "distributions",
      uiOutput("result_header"),
      tags$div(
        class = "chart-grid",
        tags$article(
          class = "chart-card",
          tags$div(
            class = "chart-title-row",
            tags$div(class = "design-marker marker-between"),
            tags$div(
              tags$h3("Between-subjects designs"),
              uiOutput("between_metric_description")
            )
          ),
          plotOutput("between_plot", height = "365px"),
          uiOutput("between_quartiles"),
          tags$div(
            class = "metric-control",
            tags$span(class = "metric-control-label", "Display as"),
            radioButtons(
              "between_metric",
              NULL,
              choices = between_metric_choices,
              selected = "r",
              inline = TRUE
            )
          )
        ),
        tags$article(
          class = "chart-card",
          tags$div(
            class = "chart-title-row",
            tags$div(class = "design-marker marker-within"),
            tags$div(
              tags$h3("Within-subjects designs"),
              tags$p("Bias-corrected effect size measured as dz")
            )
          ),
          plotOutput("within_plot", height = "365px"),
          uiOutput("within_quartiles")
        )
      ),
      tags$div(
        class = "method-note",
        tags$strong("How weighting works"),
        tags$p(
          "Bars use inverse-variance random-effects weights. Each article's ",
          "contribution is divided across its effects before bin proportions are ",
          "calculated. Dashed lines show the mean weighted quartiles from 5,000 ",
          "article-cluster bootstrap samples, with one effect sampled per ",
          "article/study. Confidence intervals are not included."
        ),
        tags$p(
          "Between-subjects conversions transform the calculated r values and ",
          "quartile thresholds while retaining the r-scale weights. The odds-ratio ",
          "histogram uses a logarithmic x-axis; on converted scales, the rightmost ",
          "bin includes values at or above its labelled boundary. The d conversion ",
          "assumes equal group sizes, r² corresponds to partial η² for one-degree-",
          "of-freedom effects, and odds ratios use the logistic approximation."
        )
      ),
      uiOutput("reproduction_download_ui")
        ),
        tabPanel("Z-curve", value = "zcurve",
          tags$article(class = "chart-card zcurve-card",
            tags$div(class = "zcurve-heading",
              tags$h3("Clustered z-curve"),
              uiOutput("zcurve_search_header")),
            tags$p(class = "input-help",
              "Two-sided p-values are calculated from r and dz with their sample sizes. ",
              "The fit uses significant effects from both designs together."),
            tags$div(class = "zcurve-layout",
              tags$div(class = "zcurve-controls",
                radioButtons("zcurve_cluster", "Cluster by",
                  choices = c("DOI" = "doi", "Unique study (DOI / study)" = "study"),
                  selected = "doi"),
                numericInput("zcurve_bootstraps", "Bootstrap samples",
                  value = 500, min = 1, max = 5000, step = 1),
                uiOutput("zcurve_fit_controls"),
                tags$details(class = "zcurve-method",
                  tags$summary("How the fit works"),
                  tags$p("The zcurve package fits z-scores from two-sided p-values ",
                    "with a nested cluster bootstrap. The plot shows its confidence ",
                    "intervals and annotations. Z-scores above 8 are capped for ",
                    "numerical stability; the calculated p-values are preserved ",
                    "in the reproduction package."))
              ),
              tags$div(class = "zcurve-visual",
                plotOutput("zcurve_plot", height = "430px"),
                uiOutput("zcurve_estimates"))
            )
          ),
          uiOutput("zcurve_download_ui")
        )
      )
    )
  )
)

server <- function(input, output, session) {
  calculation <- reactiveVal(NULL)
  zcurve_search <- reactiveVal(NULL)
  zcurve_fit <- reactiveVal(NULL)

  observeEvent(input$view, {
    updateActionButton(session, "calculate", label = if (identical(input$view, "zcurve"))
      "Search effects" else "Calculate distributions")
  })

  between_display <- reactive({
    result <- calculation()
    if (is.null(result)) {
      return(NULL)
    }
    transform_between_distribution(result$between, input$between_metric)
  })

  observeEvent(input$calculate, {
    selected <- filter_effects(
      effects,
      keyword = input$keyword,
      fields = input$field,
      conversion_bases = input$conversion_basis,
      preregistration = input$preregistration,
      year_range = input$year_range,
      journals = input$journal
    )

    filters <- list(
      keyword = trimws(input$keyword), fields = input$field,
      conversion_bases = input$conversion_basis,
      preregistration = input$preregistration,
      year_range = input$year_range, journals = input$journal
    )
    if (identical(input$view, "zcurve")) {
      zcurve_search(list(filters = filters, filtered = selected,
        prepared = prepare_zcurve_effects(selected)))
      zcurve_fit(NULL)
      return(invisible(NULL))
    }

    withProgress(message = "Calculating weighted distributions", value = 0, {
      incProgress(0.1, detail = "Filtering effects")
      between <- prepare_effect_distribution(selected, "between")
      incProgress(0.45, detail = "Between-subjects distribution")
      within <- prepare_effect_distribution(selected, "within")
      incProgress(0.45, detail = "Within-subjects distribution")

      calculation(list(
        keyword = trimws(input$keyword),
        filters = filters,
        filtered = selected,
        between = between,
        within = within
      ))
    })
  }, ignoreInit = TRUE)

  observeEvent(input$fit_zcurve, {
    search <- zcurve_search()
    req(search)
    bootstraps <- as.integer(input$zcurve_bootstraps)
    validate(need(is.finite(bootstraps) && bootstraps >= 1L && bootstraps <= 5000L,
      "Choose 1 to 5,000 bootstrap samples."))
    zcurve_fit(NULL)
    withProgress(message = "Fitting clustered z-curve", value = 0, {
      fit <- fit_clustered_zcurve(search$prepared, input$zcurve_cluster,
        bootstraps)
      fit$filters <- search$filters
      fit$prepared <- search$prepared
      zcurve_fit(fit)
    })
  })

  output$zcurve_search_header <- renderUI({
    search <- zcurve_search()
    if (is.null(search)) return(tags$span(class = "zcurve-search-prompt",
      "Search effects to see the matching count"))
    tags$div(class = "zcurve-search-counts",
      tags$strong(sprintf("%s matching effects",
        format(nrow(search$filtered), big.mark = ","))),
      tags$span(sprintf("%s p-values · %s significant (p < .05)",
        format(nrow(search$prepared), big.mark = ","),
        format(sum(search$prepared$p_value < .05), big.mark = ","))))
  })

  output$zcurve_fit_controls <- renderUI({
    search <- zcurve_search()
    if (is.null(search)) return(NULL)
    tags$div(
    if (nrow(search$filtered) > 1000L) tags$p(class = "large-fit-warning",
      sprintf("%s matching effects: fitting the requested bootstrap samples can take many minutes in your browser. Narrow the search or lower the bootstrap count for a quicker fit.",
          format(nrow(search$filtered), big.mark = ","))),
      actionButton("fit_zcurve", "Fit clustered z-curve", class = "calculate-button")
    )
  })

  output$zcurve_plot <- renderPlot(draw_zcurve(zcurve_fit()), res = 110)

  output$zcurve_estimates <- renderUI({
    fit <- zcurve_fit()
    if (is.null(fit) || !isTRUE(fit$ready)) return(NULL)
    tags$div(class = "zcurve-summary",
      tags$p(sprintf("%s significant effects across %s clusters; %s bootstrap samples. Estimates and intervals are annotated on the plot.",
        format(fit$significant, big.mark = ","), fit$clusters, fit$bootstraps)))
  })

  output$zcurve_download_ui <- renderUI({
    if (!isTRUE(zcurve_fit()$ready)) return(NULL)
    tags$div(class = "download-panel",
      tags$div(tags$strong("Reproduce this z-curve"),
        tags$p("Download the data, active filters, fitting code, and plot script.")),
      shinylive_download_button("download_zcurve", "Download reproduction package",
        class = "reproduction-button"))
  })

  output$download_zcurve <- downloadHandler(
    filename = function() paste0("zcurve-reproduction-", Sys.Date(), ".tar.gz"),
    contentType = "application/gzip",
    content = function(file) {
      fit <- zcurve_fit()
      req(fit, fit$ready)
      write_zcurve_reproduction_package(fit, file)
    })

  output$result_header <- renderUI({
    result <- calculation()
    if (is.null(result)) {
      return(tags$div(
        class = "results-intro",
        tags$div(
          tags$h2("No results calculated"),
          tags$p("Enter search terms or adjust filters, then click Calculate distributions.")
        )
      ))
    }

    search_label <- if (nzchar(result$keyword)) {
      paste0(" for “", result$keyword, "”")
    } else {
      ""
    }
    tags$div(
      class = "results-heading",
      tags$div(
        tags$p(class = "results-kicker", "RESULTS"),
        tags$h2(paste0(format(nrow(result$filtered), big.mark = ","),
          " matching effects", search_label))
      ),
      tags$div(
        class = "result-counts",
        tags$span(
          class = "count-chip chip-between",
          paste(format(result$between$usable_effects, big.mark = ","), "between")
        ),
        tags$span(
          class = "count-chip chip-within",
          paste(format(result$within$usable_effects, big.mark = ","), "within")
        )
      )
    )
  })

  output$between_plot <- renderPlot({
    specification <- between_metric_spec(input$between_metric)
    draw_effect_histogram(between_display(), "#2f6fa6", specification$x_label)
  }, res = 110)

  output$between_metric_description <- renderUI({
    tags$p(between_metric_spec(input$between_metric)$subtitle)
  })

  output$within_plot <- renderPlot({
    result <- calculation()
    distribution <- if (is.null(result)) NULL else result$within
    draw_effect_histogram(distribution, "#6a93b8", "Effect size (bias-corrected dz)")
  }, res = 110)

  output$between_quartiles <- renderUI({
    quartile_summary(between_display())
  })

  output$within_quartiles <- renderUI({
    result <- calculation()
    quartile_summary(if (is.null(result)) NULL else result$within)
  })

  output$reproduction_download_ui <- renderUI({
    if (is.null(calculation())) {
      return(NULL)
    }
    tags$div(
      class = "download-panel",
      tags$div(
        tags$strong("Reproduce this result"),
        tags$p(
          "Download the complete data and one standalone base-R script containing ",
          "the active search, filters, calculations, and plotting code."
        )
      ),
      shinylive_download_button(
        "download_reproduction",
        "Download reproduction package",
        class = "reproduction-button"
      )
    )
  })

  output$download_reproduction <- downloadHandler(
    filename = function() {
      paste0("effect-distribution-reproduction-", Sys.Date(), ".tar.gz")
    },
    contentType = "application/gzip",
    content = function(file) {
      result <- calculation()
      req(result)
      result$between_metric <- input$between_metric
      write_reproduction_package(result, file)
    }
  )
}

shinyApp(ui, server)
